### ISSUE TITLE
Problem with french accents

### ISSUE THREAD

**Issue by guidtz** [naruto-natsu/user_cas#2]
Hello,

  when I activate user_cas my full name is cut before the accent "Guillaume Ch". So with only ldap backend I have not this problem my full name is "Guillaume Chéramy".

Thanks for your help

NB : I cannot publish comment in apps.owncloud.org for this problem

**Comment by naruto-natsu** [comment]
Hello,
Character encoding problem.
it's OK now.
Thk.
